# Generated by Django 4.2.7 on 2023-11-17 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='images/campanha')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('jogador', models.ManyToManyField(blank=True, related_name='campanhas_participantes', to=settings.AUTH_USER_MODEL)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='images/personagem')),
                ('level', models.IntegerField(default=1)),
                ('ca', models.IntegerField(default=10)),
                ('vida_max', models.IntegerField(default=10)),
                ('vida', models.IntegerField(default=8)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.campanha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.sistema'),
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.campanha')),
                ('visibilidade', models.ManyToManyField(blank=True, related_name='anotacoes_visiveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
