# Generated by Django 4.2.7 on 2023-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='imagem',
            field=models.ImageField(upload_to='campanha/images/'),
        ),
    ]
