# Generated by Django 4.2.7 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_campanha_descricao_alter_campanha_imagem_postagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagem',
            name='vida_max',
        ),
        migrations.AddField(
            model_name='personagem',
            name='carisma',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='personagem',
            name='classe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personagem',
            name='constituicao',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='deslocamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personagem',
            name='destreza',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='forca',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='inteligencia',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personagem',
            name='inventario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='mh',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='perícias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personagem',
            name='raca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personagem',
            name='sabedoria',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personagem',
            name='ca',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='level',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vida',
            field=models.IntegerField(blank=True),
        ),
    ]
