# Generated by Django 4.2.7 on 2023-12-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_personagem_vida_max_personagem_carisma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='ca',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='classe',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='constituicao',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='deslocamento',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='destreza',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='forca',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='inteligencia',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='inventario',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='level',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='mh',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(default='nada', max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='perícias',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='raca',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='sabedoria',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='personagem',
            name='vida',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
