# Generated by Django 4.2.7 on 2023-12-14 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_personagem_ca_alter_personagem_classe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='perícias',
            new_name='pericias',
        ),
    ]
