# Generated by Django 4.2.1 on 2023-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_perícias_personagem_pericias'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='data_anotacao',
            field=models.DateField(auto_now_add=True, default='1999-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personagem',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
    ]
